export const tilesMockData = [
  {
    tileId: "tile_1",
    sceneRotationValues: [0, -91, 0],
    scenePositionValues: [0, 0, -7],
    sceneScaleValues: [0.03, 0.03, 0.03],
    sceneModelPath: "/models/reception_desk_diarama/reception_desk.gltf",
    sceneEnvironmentImg: "lobby",
    tilePos: [4, 0, 0],
    tilePosText: [0, 2.5, -2],
    tilePosImg: [0.5, -0.7, 0],
    tileTitle: "Reception",
    tileImgUrl: "/images/receptionIcon.jpg",
    tileHeight: 0,
    show: true,
  },
  {
    tileId: "tile_2",
    sceneRotationValues: [0, 45, 0],
    scenePositionValues: [2, 0, 18],
    sceneScaleValues: [1, 1, 1],
    sceneEnvironmentImg: "",
    sceneModelPath: "/models/hotel_room_ege_carpets_lotus_wave_grey/hotel.gltf",
    tilePos: [-8, 0, 0],
    tilePosText: [0, 2.5, -2],
    tilePosImg: [0.5, -0.7, 0],
    tileTitle: "Premium Room",
    tileImgUrl: "/images/roomIcon.jpg",
    tileHeight: -1.1,
    show: true,
  },
  {
    tileId: "tile_3",
    sceneRotationValues: [0, 0, 0],
    scenePositionValues: [-1.4, 0, 0],
    sceneScaleValues: [1.5, 1.5, 1.5],
    sceneEnvironmentImg: "",
    sceneModelPath: "/models/mini_project_bedroom_on_sketchfab/scene.gltf",
    tilePos: [-8, 0, 0],
    tilePosText: [0, 2.5, -2],
    tilePosImg: [0.5, -0.7, 0],
    tileTitle: "Standard Room",
    tileImgUrl: "/images/roomIcon2.jpg",
    tileHeight: -2.2,
    show: true,
  },
  {
    tileId: "tile_4",
    sceneRotationValues: [0, 75, 0],
    scenePositionValues: [0, 0, 1],
    sceneScaleValues: [1, 1, 1],
    sceneEnvironmentImg: "",
    sceneModelPath: "/models/premier_palace_kiev/partyhall.gltf",
    tilePos: [-2, 0, 0],
    tilePosText: [0, 2.5, -2],
    tilePosImg: [0.5, -0.7, 0],
    tileTitle: "Event Hall",
    tileImgUrl: "/images/eventHallIcon.jpg",
    tileHeight: -3.3,
    show: true,
  },
];
