export const tilesMockData = [
  {
    tileId: "tile_1",
    sceneRotationValues: [0, -91, 0],
    scenePositionValues: [0, 0, -7],
    sceneScaleValues: [0.03, 0.03, 0.03],
    sceneModelPath: "/models/reception_desk_diarama/reception_desk.gltf",
    sceneEnvironmentImg: "lobby",
    tilePos: [4, 0, 0],
    tilePosText: [0, 2.5, -2],
    tilePosImg: [0.5, -0.7, 0],
    tileTitle: "Reception",
    tileImgUrl: "/images/5.jpg",
    tileHeight: 0,
    show: true,
  },
  {
    tileId: "tile_2",
    sceneRotationValues: [0, 45, 0],
    scenePositionValues: [2, 0, 18],
    sceneScaleValues: [1, 1, 1],
    sceneEnvironmentImg: "",
    sceneModelPath: "/models/hotel_room_ege_carpets_lotus_wave_grey/hotel.gltf",
    tilePos: [-8, 0, 0],
    tilePosText: [0, 2.5, -2],
    tilePosImg: [0.5, -0.7, 0],
    tileTitle: "Room",
    tileImgUrl: "/images/2.jpg",
    tileHeight: -1.5,
    show: true,
  },
  {
    tileId: "tile_3",
    sceneRotationValues: [0, 75, 0],
    scenePositionValues: [0, 0, 1],
    sceneScaleValues: [1, 1, 1],
    sceneEnvironmentImg: "",
    sceneModelPath: "/models/premier_palace_kiev/partyhall.gltf",
    tilePos: [-2, 0, 0],
    tilePosText: [0, 2.5, -2],
    tilePosImg: [0.5, -0.7, 0],
    tileTitle: "Event Hall",
    tileImgUrl: "/images/3.jpg",
    tileHeight: -3,
    show: true,
  },
];
